// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijnsryrjyakpawmljcpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbnNyeXJqeWFrcGF3bWxqY3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mzk0ODIsImV4cCI6MjA2OTUxNTQ4Mn0.vekqoJ6go2UV8na0YCZpW1xVuFXkUtNDCf9LMoHT_hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});